teebb_core:
    #用于自动检测并获取teebb中的注解配置
    mapping:
        directories: ['%kernel.project_dir%/src']

    #邮件发送人配置此项必须配置，请修改为您的配置
    from_email:
        address: sender@quanweiwei.cn
        address_name: TEEBB.COM管理员


    fly_system:
        service: '%fly_system_service%'
        #此变量用于生成上传文件的链接
        root_host_url: '%fly_system_host%/uploads'

    #文本过滤器用于 文本已格式化字段，长文本已格式化字段，长文本已格式化字段带摘要
    filter_settings:
        strip_tags:
            filter_class: Teebb\CoreBundle\TextFilter\StripTagsFilter
            filter_label: teebb.core.form.strip_tags_filter
            extra_form_type: Symfony\Component\Form\Extension\Core\Type\TextareaType
            extra_label: teebb.core.form.strip_tags_filter_extra
            extra_help: teebb.core.form.strip_tags_filter_extra_help

        nl2br:
            filter_class: Teebb\CoreBundle\TextFilter\Nl2brFilter
            filter_label: teebb.core.form.nl2br_filter

        escape_html:
            filter_class: Teebb\CoreBundle\TextFilter\EscapeHtmlFilter
            filter_label: teebb.core.form.escape_html_filter

    #配置页面中额外的assets库，使用TemplateRegister将对应库加入页面
    assets:
        extra:
            transliteration:
                js_path: vendor/transliteration/bundle.umd.min.js

            videojs:
                js_path: vendor/video.js/video.min.js
                css_path: vendor/video.js/video-js.min.css

            sortablejs:
                js_path: vendor/sortablejs/Sortable.min.js

            autocompletejs:
                js_path: vendor/autocomplete.js/js/autocomplete.jquery.min.js

            nestable:
                js_path: vendor/nestable/jquery.nestable.js

            highlight:
                js_path: bundles/teebbcore/ckeditor-plugins/codesnippet/lib/highlight/highlight.pack.js
                css_path: bundles/teebbcore/ckeditor-plugins/codesnippet/lib/highlight/styles/dark.css

oneup_flysystem:
    adapters:
        public_dir_adapter:
            local:
                directory: '%kernel.project_dir%/public/uploads'

    filesystems:
        public_dir_filesystem:
            adapter: public_dir_adapter
            alias: League\Flysystem\Filesystem

liip_imagine:
    resolvers:
        flysystem_images_resolver:
            flysystem:
                filesystem_service: '%fly_system_service%'
                root_url:           '%fly_system_host%/uploads' #用于生成图像链接
                cache_prefix:       media/cache
                visibility:         public
    # default cache resolver for saving thumbnails
    cache: flysystem_images_resolver

    loaders:
        flysystem_images:
            flysystem:
                filesystem_service: '%fly_system_service%'
    # default loader to use for all filter sets
    data_loader: flysystem_images

    filter_sets:
        squared_thumbnail_small:
            filters:
                thumbnail:
                    size:          [100, 100]
                    mode:          outbound
                    allow_upscale: true

fos_ck_editor:
    default_config: standard
    configs:
        full:
            toolbar: full
            extraPlugins: 'codesnippet, uploadfile, uploadimage'
            uploadUrl: /file/upload
            imageUploadURL: /file/upload
            filebrowserUploadUrl: /file/upload
            filebrowserFlashUploadUrl: /file/upload
            filebrowserImageUploadUrl: /file/upload
            codeSnippet_theme: 'default'
            removePlugins: 'exportpdf'

        standard:
            toolbar: standard
            extraPlugins: 'codesnippet, uploadfile, uploadimage'
            uploadUrl: /file/upload
            imageUploadURL: /file/upload
            filebrowserUploadUrl: /file/upload
            filebrowserFlashUploadUrl: /file/upload
            filebrowserImageUploadUrl: /file/upload
            codeSnippet_theme: 'default'
            removePlugins: 'exportpdf'

        basic:
            toolbar: basic
            removePlugins: 'exportpdf'

    plugins:
        codesnippet:
            path: /bundles/teebbcore/ckeditor-plugins/codesnippet/
            filename: plugin.js
        uploadfile:
            path: /bundles/teebbcore/ckeditor-plugins/uploadfile/
            filename: plugin.js
        uploadimage:
            path: /bundles/teebbcore/ckeditor-plugins/uploadimage/
            filename: plugin.js

    toolbars:
        items:
            'full.tools': ['Maximize', 'ShowBlocks', 'CodeSnippet']
            'standard.tools': ['Maximize', 'CodeSnippet']

doctrine:
    orm:
        entity_managers:
            filters:
                filters:
                    soft-deleteable:
                        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                        enabled: true

            default:
                auto_mapping: true
                mappings:
                    gedmo_translatable:
                        type: annotation
                        prefix: Gedmo\Translatable\Entity
                        dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Translatable/Entity"
                        alias: GedmoTranslatable # (optional) it will default to the name set for the mapping
                        is_bundle: false
                    gedmo_translator:
                        type: annotation
                        prefix: Gedmo\Translator\Entity
                        dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Translator/Entity"
                        alias: GedmoTranslator # (optional) it will default to the name set for the mapping
                        is_bundle: false
                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Loggable/Entity"
                        alias: GedmoLoggable # (optional) it will default to the name set for the mapping
                        is_bundle: false
                    gedmo_tree:
                        type: annotation
                        prefix: Gedmo\Tree\Entity
                        dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Tree/Entity"
                        alias: GedmoTree # (optional) it will default to the name set for the mapping
                        is_bundle: false

#加入额外配置：控制台首页blocks和边栏菜单
imports:
    - { resource: teebb_core/ }