version: "3.8"

networks:
    backend:
volumes:
    db_volume:
    app_volume:
services:
    teebb_demo:
        build: .
        restart: always
        container_name: teebb_demo
        ports:
            - "8080:80"
        volumes:
            - app_volume:/webroot
            - ./docker-compose/teebb_demo.conf:/etc/apache2/sites-available/000-default.conf
        depends_on:
            - teebb_db
        networks:
            - backend

    teebb_db:
        image: mysql:5.7
        container_name: teebb_db
        volumes:
            - ./mysql_data:/docker-entrypoint-initdb.d
            - db_volume:/var/lib/mysql
        restart: always
        ports:
            - "8806:3306"
        environment:
            MYSQL_ROOT_PASSWORD: teebbcom
            MYSQL_DATABASE: teebb_demo
            MYSQL_USER: teebb
            MYSQL_PASSWORD: teebbcom
        networks:
            - backend