version: "3.8"
networks:
  backend:
volumes:
  app_volume:
  db_volume:
services:
  teebb_demo:
    build: .
    container_name: teebb_demo
    ports:
      - "8080:80"
    volumes:
      - app_volume:/wwwroot
      - .:/webroot
    depends_on:
      - teebb_db
    networks:
      - backend
  teebb_db:
    image: mysql:5.7
    volumes:
      - db_volume:/var/lib/mysql
    restart: always
    ports:
      - "8806:3306"
    environment:
      MYSQL_ROOT_PASSWORD: teebbcom
      MYSQL_DATABASE: teebb_demo
      MYSQL_USER: teebb
      MYSQL_PASSWORD: teebbcom
    networks:
      - backend
