_teebb_core:
    resource: .
    type: entity_type
    prefix: /admin

_teebb_content:
    resource: "@TeebbCoreBundle/Resources/config/routing/content.xml"
    prefix: /admin
    defaults:
        entity_type_service: '%entity_type.content.service%'

_teebb_comment:
    resource: "@TeebbCoreBundle/Resources/config/routing/comment.xml"
#    prefix: /admin
    defaults:
        entity_type_service: '%entity_type.comment.service%'

_teebb_taxonomy:
    resource: "@TeebbCoreBundle/Resources/config/routing/taxonomy.xml"
    prefix: /admin
    defaults:
        entity_type_service: '%entity_type.taxonomy.service%'

_teebb_user:
    resource: "@TeebbCoreBundle/Resources/config/routing/user.xml"
    prefix: /admin
    defaults:
        entity_type_service: '%entity_type.user.service%'

_teebb_file:
    resource: "@TeebbCoreBundle/Resources/config/routing/file.xml"

_teebb_formatter:
    resource: "@TeebbCoreBundle/Resources/config/routing/formatter.xml"
    prefix: /admin

_teebb_field:
    resource: "@TeebbCoreBundle/Resources/config/routing/field.xml"
    prefix: /admin

_teebb_menu:
    resource: "@TeebbCoreBundle/Resources/config/routing/menu.xml"
    prefix: /admin

_teebb_dashborad:
    resource: "@TeebbCoreBundle/Resources/config/routing/dashboard.xml"
    prefix: /admin

_teebb_options:
    resource: "@TeebbCoreBundle/Resources/config/routing/options.xml"
    prefix: /admin

security:
    resource: "@TeebbCoreBundle/Resources/config/routing/security.xml"

_teebb_front_content:
    resource: "@TeebbCoreBundle/Resources/config/routing/front.xml"